// <auto-generated />
using Meepliton.Games.SushiGo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Meepliton.Games.SushiGo.Migrations;

[DbContext(typeof(SushiGoDbContext))]
partial class SushiGoDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        // Keyless read-only platform views — not tracked by migrations
        modelBuilder.Entity("Meepliton.Games.SushiGo.Models.RoomView", b =>
        {
            b.ToTable("rooms");
            b.HasNoKey();
        });

        modelBuilder.Entity("Meepliton.Games.SushiGo.Models.RoomPlayerView", b =>
        {
            b.ToTable("room_players");
            b.HasNoKey();
        });

        modelBuilder.Entity("Meepliton.Games.SushiGo.Models.UserView", b =>
        {
            b.ToTable("users");
            b.HasNoKey();
        });
#pragma warning restore 612, 618
    }
}
