// <auto-generated />
using System;
using System.Text.Json;
using Meepliton.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Meepliton.Api.Migrations;

[DbContext(typeof(PlatformDbContext))]
partial class PlatformDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        // ── Identity: ApplicationUser (users) ────────────────────────────────

        modelBuilder.Entity("Meepliton.Api.Identity.ApplicationUser", b =>
        {
            b.Property<string>("Id").HasColumnType("text");
            b.Property<int>("AccessFailedCount").HasColumnType("integer").HasColumnName("access_failed_count");
            b.Property<string>("AvatarUrl").HasColumnType("text").HasColumnName("avatar_url");
            b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().HasColumnType("text").HasColumnName("concurrency_stamp");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at").HasDefaultValueSql("now()");
            b.Property<string>("DisplayName").IsRequired().HasColumnType("text").HasColumnName("display_name").HasDefaultValue("");
            b.Property<string>("Email").HasMaxLength(256).HasColumnType("character varying(256)").HasColumnName("email");
            b.Property<bool>("EmailConfirmed").HasColumnType("boolean").HasColumnName("email_confirmed");
            b.Property<DateTimeOffset>("LastSeenAt").HasColumnType("timestamp with time zone").HasColumnName("last_seen_at").HasDefaultValueSql("now()");
            b.Property<bool>("LockoutEnabled").HasColumnType("boolean").HasColumnName("lockout_enabled");
            b.Property<DateTimeOffset?>("LockoutEnd").HasColumnType("timestamp with time zone").HasColumnName("lockout_end");
            b.Property<string>("NormalizedEmail").HasMaxLength(256).HasColumnType("character varying(256)").HasColumnName("normalized_email");
            b.Property<string>("NormalizedUserName").HasMaxLength(256).HasColumnType("character varying(256)").HasColumnName("normalized_user_name");
            b.Property<string>("PasswordHash").HasColumnType("text").HasColumnName("password_hash");
            b.Property<string>("PhoneNumber").HasColumnType("text").HasColumnName("phone_number");
            b.Property<bool>("PhoneNumberConfirmed").HasColumnType("boolean").HasColumnName("phone_number_confirmed");
            b.Property<string>("SecurityStamp").HasColumnType("text").HasColumnName("security_stamp");
            b.Property<string>("Theme").IsRequired().HasColumnType("text").HasColumnName("theme").HasDefaultValue("system");
            b.Property<bool>("TwoFactorEnabled").HasColumnType("boolean").HasColumnName("two_factor_enabled");
            b.Property<string>("UserName").HasMaxLength(256).HasColumnType("character varying(256)").HasColumnName("user_name");
            b.HasKey("Id").HasName("pk_users");
            b.HasIndex("NormalizedEmail").HasDatabaseName("ix_users_normalized_email");
            b.HasIndex("NormalizedUserName").IsUnique().HasDatabaseName("ix_users_normalized_user_name");
            b.ToTable("users");
        });

        // ── Identity: IdentityRole (roles) ───────────────────────────────────

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
        {
            b.Property<string>("Id").HasColumnType("text");
            b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().HasColumnType("text").HasColumnName("concurrency_stamp");
            b.Property<string>("Name").HasMaxLength(256).HasColumnType("character varying(256)").HasColumnName("name");
            b.Property<string>("NormalizedName").HasMaxLength(256).HasColumnType("character varying(256)").HasColumnName("normalized_name");
            b.HasKey("Id").HasName("pk_roles");
            b.HasIndex("NormalizedName").IsUnique().HasDatabaseName("ix_roles_normalized_name");
            b.ToTable("roles");
        });

        // ── Identity: IdentityRoleClaim (role_claims) ────────────────────────

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer").HasColumnName("id");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
            b.Property<string>("ClaimType").HasColumnType("text").HasColumnName("claim_type");
            b.Property<string>("ClaimValue").HasColumnType("text").HasColumnName("claim_value");
            b.Property<string>("RoleId").IsRequired().HasColumnType("text").HasColumnName("role_id");
            b.HasKey("Id").HasName("pk_role_claims");
            b.HasIndex("RoleId").HasDatabaseName("ix_role_claims_role_id");
            b.ToTable("role_claims");
        });

        // ── Identity: IdentityUserClaim (user_claims) ────────────────────────

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer").HasColumnName("id");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
            b.Property<string>("ClaimType").HasColumnType("text").HasColumnName("claim_type");
            b.Property<string>("ClaimValue").HasColumnType("text").HasColumnName("claim_value");
            b.Property<string>("UserId").IsRequired().HasColumnType("text").HasColumnName("user_id");
            b.HasKey("Id").HasName("pk_user_claims");
            b.HasIndex("UserId").HasDatabaseName("ix_user_claims_user_id");
            b.ToTable("user_claims");
        });

        // ── Identity: IdentityUserLogin (user_logins) ────────────────────────

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
        {
            b.Property<string>("LoginProvider").HasColumnType("text").HasColumnName("login_provider");
            b.Property<string>("ProviderKey").HasColumnType("text").HasColumnName("provider_key");
            b.Property<string>("ProviderDisplayName").HasColumnType("text").HasColumnName("provider_display_name");
            b.Property<string>("UserId").IsRequired().HasColumnType("text").HasColumnName("user_id");
            b.HasKey("LoginProvider", "ProviderKey").HasName("pk_user_logins");
            b.HasIndex("UserId").HasDatabaseName("ix_user_logins_user_id");
            b.ToTable("user_logins");
        });

        // ── Identity: IdentityUserRole (user_roles) ──────────────────────────

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
        {
            b.Property<string>("UserId").HasColumnType("text").HasColumnName("user_id");
            b.Property<string>("RoleId").HasColumnType("text").HasColumnName("role_id");
            b.HasKey("UserId", "RoleId").HasName("pk_user_roles");
            b.HasIndex("RoleId").HasDatabaseName("ix_user_roles_role_id");
            b.ToTable("user_roles");
        });

        // ── Identity: IdentityUserToken (user_tokens) ────────────────────────

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
        {
            b.Property<string>("UserId").HasColumnType("text").HasColumnName("user_id");
            b.Property<string>("LoginProvider").HasColumnType("text").HasColumnName("login_provider");
            b.Property<string>("Name").HasColumnType("text").HasColumnName("name");
            b.Property<string>("Value").HasColumnType("text").HasColumnName("value");
            b.HasKey("UserId", "LoginProvider", "Name").HasName("pk_user_tokens");
            b.ToTable("user_tokens");
        });

        // ── Platform: Game ────────────────────────────────────────────────────

        modelBuilder.Entity("Meepliton.Api.Models.Game", b =>
        {
            b.Property<string>("Id").HasColumnType("text");
            b.Property<string>("Description").IsRequired().HasColumnType("text").HasColumnName("description").HasDefaultValue("");
            b.Property<int>("MaxPlayers").HasColumnType("integer").HasColumnName("max_players");
            b.Property<int>("MinPlayers").HasColumnType("integer").HasColumnName("min_players");
            b.Property<string>("Name").IsRequired().HasColumnType("text").HasColumnName("name");
            b.Property<string>("ThumbnailUrl").HasColumnType("text").HasColumnName("thumbnail_url");
            b.HasKey("Id").HasName("pk_games");
            b.ToTable("games");
        });

        // ── Platform: Room ────────────────────────────────────────────────────

        modelBuilder.Entity("Meepliton.Api.Models.Room", b =>
        {
            b.Property<string>("Id").HasColumnType("text");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at").HasDefaultValueSql("now()");
            b.Property<DateTimeOffset?>("ExpiresAt").HasColumnType("timestamp with time zone").HasColumnName("expires_at");
            b.Property<string>("GameId").IsRequired().HasColumnType("text").HasColumnName("game_id");
            b.Property<JsonDocument>("GameOptions").HasColumnType("jsonb").HasColumnName("game_options");
            b.Property<JsonDocument>("GameState").HasColumnType("jsonb").HasColumnName("game_state");
            b.Property<string>("HostId").IsRequired().HasColumnType("text").HasColumnName("host_id");
            b.Property<string>("JoinCode").IsRequired().IsFixedLength().HasMaxLength(6).HasColumnType("character(6)").HasColumnName("join_code");
            b.Property<int>("StateVersion").HasColumnType("integer").HasColumnName("state_version");
            b.Property<string>("Status").IsRequired().HasColumnType("text").HasColumnName("status").HasDefaultValue("Waiting");
            b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamp with time zone").HasColumnName("updated_at").HasDefaultValueSql("now()");
            b.HasKey("Id").HasName("pk_rooms");
            b.HasIndex("ExpiresAt").HasDatabaseName("ix_rooms_expires_at");
            b.HasIndex("JoinCode").IsUnique().HasDatabaseName("ix_rooms_join_code");
            b.HasIndex("Status").HasDatabaseName("ix_rooms_status");
            b.ToTable("rooms");
        });

        // ── Platform: RoomPlayer ─────────────────────────────────────────────

        modelBuilder.Entity("Meepliton.Api.Models.RoomPlayer", b =>
        {
            b.Property<string>("Id").HasColumnType("text");
            b.Property<DateTimeOffset>("JoinedAt").HasColumnType("timestamp with time zone").HasColumnName("joined_at").HasDefaultValueSql("now()");
            b.Property<string>("RoomId").IsRequired().HasColumnType("text").HasColumnName("room_id");
            b.Property<int>("SeatIndex").HasColumnType("integer").HasColumnName("seat_index");
            b.Property<string>("UserId").IsRequired().HasColumnType("text").HasColumnName("user_id");
            b.HasKey("Id").HasName("pk_room_players");
            b.HasIndex("RoomId").HasDatabaseName("ix_room_players_room_id");
            b.HasIndex("UserId").HasDatabaseName("ix_room_players_user_id");
            b.ToTable("room_players");
        });

        // ── Platform: ActionLog ───────────────────────────────────────────────

        modelBuilder.Entity("Meepliton.Api.Models.ActionLog", b =>
        {
            b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint").HasColumnName("id");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));
            b.Property<JsonDocument>("Action").IsRequired().HasColumnType("jsonb").HasColumnName("action");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at").HasDefaultValueSql("now()");
            b.Property<string>("PlayerId").IsRequired().HasColumnType("text").HasColumnName("player_id");
            b.Property<string>("RoomId").IsRequired().HasColumnType("text").HasColumnName("room_id");
            b.Property<int>("StateVersion").HasColumnType("integer").HasColumnName("state_version");
            b.HasKey("Id").HasName("pk_action_log");
            b.HasIndex("RoomId").HasDatabaseName("ix_action_log_room_id");
            b.ToTable("action_log");
        });

        // ── Foreign-key relationships ─────────────────────────────────────────

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
        {
            b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
             .WithMany()
             .HasForeignKey("RoleId")
             .OnDelete(DeleteBehavior.Cascade)
             .IsRequired();
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
        {
            b.HasOne("Meepliton.Api.Identity.ApplicationUser", null)
             .WithMany()
             .HasForeignKey("UserId")
             .OnDelete(DeleteBehavior.Cascade)
             .IsRequired();
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
        {
            b.HasOne("Meepliton.Api.Identity.ApplicationUser", null)
             .WithMany()
             .HasForeignKey("UserId")
             .OnDelete(DeleteBehavior.Cascade)
             .IsRequired();
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
        {
            b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
             .WithMany()
             .HasForeignKey("RoleId")
             .OnDelete(DeleteBehavior.Cascade)
             .IsRequired();
            b.HasOne("Meepliton.Api.Identity.ApplicationUser", null)
             .WithMany()
             .HasForeignKey("UserId")
             .OnDelete(DeleteBehavior.Cascade)
             .IsRequired();
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
        {
            b.HasOne("Meepliton.Api.Identity.ApplicationUser", null)
             .WithMany()
             .HasForeignKey("UserId")
             .OnDelete(DeleteBehavior.Cascade)
             .IsRequired();
        });

#pragma warning restore 612, 618
    }
}
