// <auto-generated />
using System;
using Meepliton.Games.Skyline;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Meepliton.Games.Skyline.Migrations;

[DbContext(typeof(SkylineDbContext))]
partial class SkylineDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Meepliton.Games.Skyline.Models.SkylineGameResult", b =>
        {
            b.Property<long>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("bigint")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            b.Property<DateTimeOffset>("CompletedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("FinalScores")
                .IsRequired()
                .HasColumnType("jsonb");

            b.Property<string>("RoomId")
                .IsRequired()
                .HasColumnType("text");

            b.Property<string>("WinnerId")
                .HasColumnType("text");

            b.HasKey("Id");

            b.ToTable("skyline_game_results");
        });

        modelBuilder.Entity("Meepliton.Games.Skyline.Models.SkylinePlayerStats", b =>
        {
            b.Property<string>("Id")
                .HasColumnType("text");

            b.Property<int>("GamesPlayed")
                .HasColumnType("integer");

            b.Property<int>("GamesWon")
                .HasColumnType("integer");

            b.Property<DateTimeOffset?>("LastPlayedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<long>("TotalScore")
                .HasColumnType("bigint");

            b.Property<string>("UserId")
                .IsRequired()
                .HasColumnType("text");

            b.HasKey("Id");

            b.ToTable("skyline_player_stats");
        });

        // Keyless read-only platform views — not tracked by migrations
        modelBuilder.Entity("Meepliton.Games.Skyline.Models.RoomView", b =>
        {
            b.ToTable("rooms");
            b.HasNoKey();
        });

        modelBuilder.Entity("Meepliton.Games.Skyline.Models.RoomPlayerView", b =>
        {
            b.ToTable("room_players");
            b.HasNoKey();
        });

        modelBuilder.Entity("Meepliton.Games.Skyline.Models.UserView", b =>
        {
            b.ToTable("users");
            b.HasNoKey();
        });
#pragma warning restore 612, 618
    }
}
